### ISSUE TITLE
saying it needs to be updated but there is no way to update it 

### ISSUE THREAD

**Issue by polofv1** [KingContaria/SpeedrunAPI#6]

**Comment by KingContaria** [comment]
I am assuming you are using MCSR Ranked. Ranked has a whitelist, which their developers add new mod versions to when they're released. Sometimes this takes a while, but they will be updated eventually. When the text in the window says "whitelist" somewhere in it, that points to this being the case.
In the future, please desrcibe your issue in more detail and consider adding important files (like a screenshot and/or log file) to your message :)
