### ISSUE TITLE
Uncompatibility of speedrunapi-1.0.1+1.16.1.jar and fast-reset-2.1+1.16.1.jar (?)

### ISSUE THREAD

**Issue by personalfebus** [KingContaria/SpeedrunAPI#7]
Hello, there already is a similar issue, which lacks a lot of context and explanation - https://github.com/KingContaria/SpeedrunAPI/issues/6
Some context can be found here - https://www.reddit.com/r/MinecraftSpeedrun/comments/1eziklm/this_happens_when_i_try_to_launch_mcsr_ranked/

The issue: Freshly downloaded mcsr instance will not launch (with the exception shown in reddit post). I managed to fix it for myself by downgrading fastreset and speedrun-api (since i saw, that the versions were bumped recently https://github.com/Minecraft-Java-Edition-Speedrunning/legal-mods/pull/78). There might be compatibility or validation issues

**Comment by KingContaria** [comment]
At the time of this issue Ranked hadn't whitelisted the new mod versions yet (although I think that's fixed in the new version), please report issues where it says "whitelisted" to MCSR Ranked in the future :)
