### ISSUE TITLE
compat plugin will not work for modids with dashes

### ISSUE THREAD

**Issue by tildejustin** [KingContaria/SpeedrunAPI#8]
https://github.com/KingContaria/SpeedrunAPI/blob/b85577b6e0a0d7faca296cd1862eef3e6c61ae66/src/main/java/org/mcsr/speedrunapi/mixin_plugin/SpeedrunMixinConfigPlugin.java#L33-L37

the code to apply compat classes has a potential problem: packages, unlike modids, can contain dashes. this hasn't been an issue yet but this is pretty common for fabric mods. the solution i see is to take the candidate modid and check against a modification of it with underscores replaced with dashes as well. this will allow minimal unreliability on the part of any java packages. the only downside is this still would not work for mods that use both dashes and underscores, however i consider this an unnecessarily theoretical issue. the dollar sign is technically an allowed character that could probably be used for direct substitution as it isn't valid in modids, however it confuses mc-dev and by making class hierarchies unable to be easily parsed so i would recommend against it.

a word of warning: IMixinConfigPlugin#shouldApplyMixin has a potentially undesirable trait. it force-applies a mixin, even if the target class isn't present. if at all possible, checking for if the desired class is loaded on top of the modid could be useful, i'm unsure if preapply is run before shouldApply so this may not be possible. this was an issue i ran into with srigt and sodium already https://github.com/RedLime/SpeedRunIGT/pull/202#issuecomment-2259268501.

**Comment by KingContaria** [comment]
> a word of warning: IMixinConfigPlugin#shouldApplyMixin has a potentially undesirable trait. it force-applies a mixin, even if the target class isn't present. if at all possible, checking for if the desired class is loaded on top of the modid could be useful, i'm unsure if preapply is run before shouldApply so this may not be possible. this was an issue i ran into with srigt and sodium already https://github.com/RedLime/SpeedRunIGT/pull/202#issuecomment-2259268501.

Could you create a seperate issue for this?

**Comment by KingContaria** [comment]
Would this cover the cases you can think of?
```
    @Override
    public boolean shouldApplyMixin(String targetClassName, String mixinClassName) {
        String compatPackage = this.mixinPackage + ".compat.";
        if (mixinClassName.startsWith(compatPackage)) {
            String modid = mixinClassName.replaceFirst(compatPackage, "").split("\\.", 2)[0];
            for (ModContainer mod : FabricLoader.getInstance().getAllMods()) {
                if (mod.getMetadata().getId().replaceAll("-", "_").equals(modid)) {
                    return true;
                }
            }
            return false;
        }
        return true;
    }
```
